{% set name = "exonote" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/exonote-{{ version }}.tar.gz
  sha256: 97ec5113ba2341dc033693ad120c58fb475f70782ba114cc56cad548063163f0

build:
  entry_points:
    - exonote = exonote.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - oscan
    - tkutil

test:
  imports:
    - exonote
  commands:
    - pip check
    - exonote --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/exonote
  summary: Backend for exn; write and render rich, scriptable, and interactive notes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
